# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from omnigent.api.hiloop.v1 import sandbox_session_pb2 as omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in omnigent/api/hiloop/v1/sandbox_session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxSessionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandboxSession = channel.unary_unary(
                '/hiloop.api.v1.SandboxSessionService/CreateSandboxSession',
                request_serializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.CreateSandboxSessionRequest.SerializeToString,
                response_deserializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.CreateSandboxSessionResponse.FromString,
                _registered_method=True)
        self.GetSandboxSession = channel.unary_unary(
                '/hiloop.api.v1.SandboxSessionService/GetSandboxSession',
                request_serializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.GetSandboxSessionRequest.SerializeToString,
                response_deserializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.GetSandboxSessionResponse.FromString,
                _registered_method=True)
        self.RevokeSandboxSession = channel.unary_unary(
                '/hiloop.api.v1.SandboxSessionService/RevokeSandboxSession',
                request_serializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.RevokeSandboxSessionRequest.SerializeToString,
                response_deserializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.RevokeSandboxSessionResponse.FromString,
                _registered_method=True)


class SandboxSessionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSandboxSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandboxSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeSandboxSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxSessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandboxSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandboxSession,
                    request_deserializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.CreateSandboxSessionRequest.FromString,
                    response_serializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.CreateSandboxSessionResponse.SerializeToString,
            ),
            'GetSandboxSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandboxSession,
                    request_deserializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.GetSandboxSessionRequest.FromString,
                    response_serializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.GetSandboxSessionResponse.SerializeToString,
            ),
            'RevokeSandboxSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeSandboxSession,
                    request_deserializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.RevokeSandboxSessionRequest.FromString,
                    response_serializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.RevokeSandboxSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hiloop.api.v1.SandboxSessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hiloop.api.v1.SandboxSessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxSessionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSandboxSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hiloop.api.v1.SandboxSessionService/CreateSandboxSession',
            omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.CreateSandboxSessionRequest.SerializeToString,
            omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.CreateSandboxSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandboxSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hiloop.api.v1.SandboxSessionService/GetSandboxSession',
            omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.GetSandboxSessionRequest.SerializeToString,
            omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.GetSandboxSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeSandboxSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hiloop.api.v1.SandboxSessionService/RevokeSandboxSession',
            omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.RevokeSandboxSessionRequest.SerializeToString,
            omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.RevokeSandboxSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SandboxSessionConnectServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.stream_stream(
                '/hiloop.api.v1.SandboxSessionConnectService/Open',
                request_serializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.OpenRequest.SerializeToString,
                response_deserializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.OpenResponse.FromString,
                _registered_method=True)


class SandboxSessionConnectServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Open(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxSessionConnectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.stream_stream_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.OpenRequest.FromString,
                    response_serializer=omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.OpenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hiloop.api.v1.SandboxSessionConnectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hiloop.api.v1.SandboxSessionConnectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxSessionConnectService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Open(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hiloop.api.v1.SandboxSessionConnectService/Open',
            omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.OpenRequest.SerializeToString,
            omnigent_dot_api_dot_hiloop_dot_v1_dot_sandbox__session__pb2.OpenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
